version: 2
updates:
  # Composerの依存関係をチェック
  - package-ecosystem: "composer"
    directory: "/" # composer.jsonがある場所
    schedule:
      interval: "daily"
  
  # GitHub Actionsの依存関係をチェック
  - package-ecosystem: "github-actions"
    directory: "/" # ワークフローファイルがある場所
    schedule:
      interval: "daily"
