name: Build Website

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl, curl, json
          tools: composer:v2
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress

      # ★★★ ここからが変更点 ★★★
      - name: Run Site Generator Script
        id: generator # このステップにIDを付ける
        continue-on-error: true # このステップが失敗しても、ワークフローを止めない
        env:
          PAAPI_ACCESS_KEY: ${{ secrets.PAAPI_ACCESS_KEY }}
          PAAPI_SECRET_KEY: ${{ secrets.PAAPI_SECRET_KEY }}
          PAAPI_ASSOCIATE_TAG: ${{ secrets.PAAPI_ASSOCIATE_TAG }}
        run: php generate.php

      - name: Check build status and copy placeholder if failed
        # 上の 'generator' ステップが失敗した場合にのみ、このステップを実行する
        if: steps.generator.outcome == 'failure'
        run: |
          echo "Site generation failed. Copying placeholder page."
          # publicフォルダがなければ作成
          mkdir -p public
          # placeholder/index.html を public/index.html にコピーする
          cp placeholder/index.html public/index.html
      # ★★★ 変更ここまで ★★★

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./public
