name: Build Website

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl
          tools: composer:v2
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run Site Generator Script
        env:
          PAAPI_ACCESS_KEY: ${{ secrets.PAAPI_ACCESS_KEY }}
          PAAPI_SECRET_KEY: ${{ secrets.PAAPI_SECRET_KEY }}
          PAAPI_ASSOCIATE_TAG: ${{ secrets.PAAPI_ASSOCIATE_TAG }}
        run: php generate.php

      # ★★★ ここからデバッグ用ステップ ★★★
      - name: Check PHP script output
        run: |
          echo "--- PHP script execution finished ---"
          echo "Checking if public directory exists..."
          if [ -d "public" ]; then echo "OK: 'public' directory exists."; else echo "ERROR: 'public' directory does NOT exist."; fi

      - name: List files in public directory
        run: |
          echo "--- Listing files in the public directory ---"
          ls -la public
      # ★★★ デバッグ用ステップここまで ★★★

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./public
